"""Alembic environment configuration.

Wires Alembic to the application's settings (``app.core.config``) and
models (``app.models``), so migrations are generated by comparing the
real SQLAlchemy metadata against the database — never written by hand
from scratch. See ``docs/006-BaseDatos/03-Estrategia-de-Migraciones.md``.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Alembic runs synchronously; psycopg 3 supports both sync and async with
# the same "postgresql+psycopg" dialect, so no separate sync driver needed.
settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database_url_async)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations without a live DB connection (generates raw SQL)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
